// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3s0S1XYNVOsjUUq0vO9EL0DKcXcoWXpg',
    appId: '1:30977785866:web:e251780b27e94923185ff3',
    messagingSenderId: '30977785866',
    projectId: 'fir-bookmark-618ef',
    authDomain: 'fir-bookmark-618ef.firebaseapp.com',
    storageBucket: 'fir-bookmark-618ef.appspot.com',
    measurementId: 'G-LPXQDW9QML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnuE9tzJdd9pIfsEpQ8ykcEqKo1AXqNJk',
    appId: '1:30977785866:android:3d028ba8e82dda66185ff3',
    messagingSenderId: '30977785866',
    projectId: 'fir-bookmark-618ef',
    storageBucket: 'fir-bookmark-618ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyEUVcAc63wjJC4WTK6dCVLERbWP8IM8',
    appId: '1:30977785866:ios:f59c77a540911bd4185ff3',
    messagingSenderId: '30977785866',
    projectId: 'fir-bookmark-618ef',
    storageBucket: 'fir-bookmark-618ef.appspot.com',
    iosBundleId: 'com.example.instagramUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASyEUVcAc63wjJC4WTK6dCVLERbWP8IM8',
    appId: '1:30977785866:ios:27913cc4657dc97b185ff3',
    messagingSenderId: '30977785866',
    projectId: 'fir-bookmark-618ef',
    storageBucket: 'fir-bookmark-618ef.appspot.com',
    iosBundleId: 'com.example.instagramUi.RunnerTests',
  );
}
